feat: Update favicon
BiiLabs/biilabs.io pull request #22
Opened 2020-08-21 06:37 UTC by cyh0530

2020-08-21 06:46 UTC, jserv requested changes
Mention the motivation, such as reflecting the latest visual design.

2020-08-21 08:26 UTC, cyh0530 commented
I have updated the information.

2020-08-21 15:06 UTC, jserv approved these changes

2020-08-22 03:24 UTC, junwei0117 approved these changes

2020-08-22 03:24 UTC, merged